version: '3.7'

services:
  logspout:
    build:
      context: extensions/logspout
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      ROUTE_URIS: logstash://logstash:50000
      LOGSTASH_TAGS: docker-elk
    networks:
      private:
        ipv4_address: 192.168.0.104
    depends_on:
      - logstash
    restart: on-failure
